# Generated by Django 4.2.7 on 2023-11-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_NamePr', models.CharField(max_length=200)),
                ('Sale_QuantityPr', models.BigIntegerField(max_length=9223372036854775807)),
                ('Sale_PricePr', models.CharField(max_length=200)),
                ('Sale_Date', models.DateField(auto_now=True)),
                ('Sale_NameSalesman', models.CharField(max_length=200)),
            ],
        ),
    ]
